In [1]:
## numpy的一些基本操作
## 参考100 numpy exercise: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

import numpy as np

# 1.创建长度为10的一维0向量
Zero = np.zeros(10)
print(Zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
# 2.生成一个值在[10, 49]的向量，再翻转
random_vector = np.arange(10, 50)
print(random_vector)
reverse_vector = random_vector[::-1]
print(reverse_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [3]:
# 3.生成一个3*3的向量，值在0-8
two_dim_vec = np.arange(9).reshape(3, 3)
print(two_dim_vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4.找出列表中非零项元素的索引
nz = np.nonzero([1, 2, 0, 0, 4, 0, 1, 0])
print(nz)

(array([0, 1, 4, 6]),)


In [5]:
# 5.创建一个3阶单位矩阵
ni3 = np.eye(3)
print(ni3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# 6.在一个已有的矩阵上增加一个边界（比如边界都为0）
no5 = np.ones((5, 5))
print(no5)
no5 = np.pad(no5, pad_width=1, mode='constant', constant_values=0)
print(no5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
