In [1]:
## numpy的一些基本操作
## 参考100 numpy exercise: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

import numpy as np

# 1.创建长度为10的一维0向量
Zero = np.zeros(10)
print(Zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
# 2.生成一个值在[10, 49]的向量，再翻转
random_vector = np.arange(10, 50)
print(random_vector)
reverse_vector = random_vector[::-1]
print(reverse_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [3]:
# 3.生成一个3*3的向量，值在0-8
two_dim_vec = np.arange(9).reshape(3, 3)
print(two_dim_vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4.找出列表中非零项元素的索引
nz = np.nonzero([1, 2, 0, 0, 4, 0, 1, 0])
print(nz)

(array([0, 1, 4, 6]),)


In [5]:
# 5.创建一个3阶单位矩阵
ni3 = np.eye(3)
print(ni3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# 6.在一个已有的矩阵上增加一个边界（比如边界都为0）
no5 = np.ones((5, 5))
print(no5)
no5 = np.pad(no5, pad_width=1, mode='constant', constant_values=0)
print(no5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
# 7.在6*7*8的矩阵中第100个元素的索引
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [8]:
# 8.标准化一个5*5的随机矩阵
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.35970547 -1.07092522  1.04011819  0.44952082  1.58494228]
 [ 0.86395814  0.97106493 -0.04453974 -1.69008981 -0.83938591]
 [-1.62061711  0.28337144  1.07429919 -1.47458605 -0.07327108]
 [-0.73354092 -0.07964248  0.46016963  0.46684552 -1.6823213 ]
 [-0.27738803  0.67805876  1.24793572 -1.11534515  1.22166271]]


In [9]:
# 9.5*3的矩阵和3*2的矩阵相乘
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [10]:
# 10.求两个列表的交集
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[4 2 0 7 7 5 7 0 6 6]
[7 5 6 6 7 1 3 8 2 5]
[2 5 6 7]


In [11]:
# 11.计算昨天，今天，明天的日期
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-02-10
2019-02-11
2019-02-12


In [12]:
# 12.求一个小数的整数部分
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[7.46481209 9.76257142 0.3890991  3.02344398 6.79122362 6.30145019
 4.2568393  8.20926196 9.16554066 3.9736453 ]
[7. 9. 0. 3. 6. 6. 4. 8. 9. 3.]
[7. 9. 0. 3. 6. 6. 4. 8. 9. 3.]
[7. 9. 0. 3. 6. 6. 4. 8. 9. 3.]
[7 9 0 3 6 6 4 8 9 3]
[7. 9. 0. 3. 6. 6. 4. 8. 9. 3.]


In [13]:
# 13.向量中最大值替换为0
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.69218607 0.7503235  0.         0.27870677 0.37562777 0.74560716
 0.63375753 0.45998546 0.59121773 0.60544646]
