In [1]:
## numpy的一些基本操作
## 参考100 numpy exercise: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

import numpy as np

# 1.创建长度为10的一维0向量
Zero = np.zeros(10)
print(Zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
# 2.生成一个值在[10, 49]的向量，再翻转
random_vector = np.arange(10, 50)
print(random_vector)
reverse_vector = random_vector[::-1]
print(reverse_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [3]:
# 3.生成一个3*3的向量，值在0-8
two_dim_vec = np.arange(9).reshape(3, 3)
print(two_dim_vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4.找出列表中非零项元素的索引
nz = np.nonzero([1, 2, 0, 0, 4, 0, 1, 0])
print(nz)

(array([0, 1, 4, 6]),)


In [5]:
# 5.创建一个3阶单位矩阵
ni3 = np.eye(3)
print(ni3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# 6.在一个已有的矩阵上增加一个边界（比如边界都为0）
no5 = np.ones((5, 5))
print(no5)
no5 = np.pad(no5, pad_width=1, mode='constant', constant_values=0)
print(no5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
# 7.在6*7*8的矩阵中第100个元素的索引
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [8]:
# 8.标准化一个5*5的随机矩阵
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.42863225 -1.77041971  1.13147763  1.24980435  0.49308429]
 [-0.23854976 -1.5073882   1.27049104  0.28152825 -0.45312767]
 [-0.71491042 -0.78316955 -1.2232094   0.70248052  0.98846025]
 [ 1.24438197 -1.64532938  0.1002207   0.4229643   0.55232432]
 [ 0.75638781 -1.70733038  1.36312644 -0.34151927  0.25685411]]


In [9]:
# 9.5*3的矩阵和3*2的矩阵相乘
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [10]:
# 10.求两个列表的交集
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[3 4 6 3 4 4 1 4 8 0]
[8 6 5 0 5 3 4 8 9 1]
[0 1 3 4 6 8]


In [11]:
# 11.计算昨天，今天，明天的日期
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-02-14
2019-02-15
2019-02-16


In [12]:
# 12.求一个小数的整数部分
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1.70059627 3.9652985  9.31320348 5.20107801 2.75064036 6.43351916
 6.33391494 9.3548741  6.57617137 6.9375355 ]
[1. 3. 9. 5. 2. 6. 6. 9. 6. 6.]
[1. 3. 9. 5. 2. 6. 6. 9. 6. 6.]
[1. 3. 9. 5. 2. 6. 6. 9. 6. 6.]
[1 3 9 5 2 6 6 9 6 6]
[1. 3. 9. 5. 2. 6. 6. 9. 6. 6.]


In [13]:
# 13.向量中最大值替换为0
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.4113835  0.81780658 0.87409677 0.86171913 0.         0.08864539
 0.86457015 0.80668016 0.75838696 0.82486218]


In [14]:
# 14.将一个32位浮点型列表改为整型
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# 15.遍历numpy数组元素并求出index
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [16]:
# 16.在二维数组中随机替换p个元素
n, p = 10, 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
Z = np.random.randint(0,10,(3,3))
print(Z)
# 17.根据列来排序
print(Z[Z[:,0].argsort()])
# 18.根据行来排序
print(Z[Z[:,1].argsort()])

[[9 5 4]
 [2 7 6]
 [2 2 8]]
[[2 7 6]
 [2 2 8]
 [9 5 4]]
[[2 2 8]
 [9 5 4]
 [2 7 6]]


In [19]:
# 19.给定一个值，找出它最接近的值
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.81177176 0.92651691 0.2803455  0.39215195 0.09521935 0.30840965
 0.69795514 0.36270317 0.97677082 0.77534189]
0.3921519495808411
