In [2]:
## numpy的一些基本操作
## 参考100 numpy exercise: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

import numpy as np

# 1.创建长度为10的一维0向量
Zero = np.zeros(10)
print(Zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# 2.生成一个值在[10, 49]的向量，再翻转
random_vector = np.arange(10, 50)
print(random_vector)
reverse_vector = random_vector[::-1]
print(reverse_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [4]:
# 3.生成一个3*3的向量，值在0-8
two_dim_vec = np.arange(9).reshape(3, 3)
print(two_dim_vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# 4.找出列表中非零项元素的索引
nz = np.nonzero([1, 2, 0, 0, 4, 0, 1, 0])
print(nz)

(array([0, 1, 4, 6]),)


In [6]:
# 5.创建一个3阶单位矩阵
ni3 = np.eye(3)
print(ni3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# 6.在一个已有的矩阵上增加一个边界（比如边界都为0）
no5 = np.ones((5, 5))
print(no5)
no5 = np.pad(no5, pad_width=1, mode='constant', constant_values=0)
print(no5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [8]:
# 7.在6*7*8的矩阵中第100个元素的索引
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [9]:
# 8.标准化一个5*5的随机矩阵
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.99610222  0.29315123  0.87541644  1.26650842  0.94227658]
 [-0.68159098  0.10229637  1.65872235 -0.79528156 -0.76791866]
 [-1.4224365  -0.20085966 -0.73961938 -1.21962737  1.53941247]
 [-0.11816111  0.16838647  1.31740948 -1.32021309 -1.46142138]
 [ 0.46262438  0.80775467  1.45415156 -0.1182769  -1.0466016 ]]


In [10]:
# 9.5*3的矩阵和3*2的矩阵相乘
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [11]:
# 10.求两个列表的交集
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[8 7 7 2 8 4 0 3 8 2]
[6 9 5 3 5 7 3 0 4 4]
[0 3 4 7]


In [12]:
# 11.计算昨天，今天，明天的日期
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-02-21
2019-02-22
2019-02-23


In [13]:
# 12.求一个小数的整数部分
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[5.17241162 2.22369571 0.6401267  8.05312264 8.76878538 9.66536617
 4.61927252 5.11563741 1.06410135 6.38633412]
[5. 2. 0. 8. 8. 9. 4. 5. 1. 6.]
[5. 2. 0. 8. 8. 9. 4. 5. 1. 6.]
[5. 2. 0. 8. 8. 9. 4. 5. 1. 6.]
[5 2 0 8 8 9 4 5 1 6]
[5. 2. 0. 8. 8. 9. 4. 5. 1. 6.]


In [14]:
# 13.向量中最大值替换为0
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.17015084 0.79337141 0.32738456 0.50730394 0.         0.47191745
 0.44404164 0.32572959 0.02244862 0.31765436]


In [15]:
# 14.将一个32位浮点型列表改为整型
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# 15.遍历numpy数组元素并求出index
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [17]:
# 16.在二维数组中随机替换p个元素
n, p = 10, 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
Z = np.random.randint(0,10,(3,3))
print(Z)
# 17.根据列来排序
print(Z[Z[:,0].argsort()])
# 18.根据行来排序
print(Z[Z[:,1].argsort()])

[[8 5 0]
 [9 1 9]
 [3 1 6]]
[[3 1 6]
 [8 5 0]
 [9 1 9]]
[[9 1 9]
 [3 1 6]
 [8 5 0]]


In [19]:
# 19.给定一个值，找出它最接近的值
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.8107861  0.37817955 0.84301537 0.69813038 0.83498317 0.67487889
 0.87366829 0.71500303 0.25101715 0.05785908]
0.378179545380399


In [22]:
# 20.求两个方阵乘积的对角线上的值
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)

# Slow version  
d1 = np.diag(np.dot(A, B))
print(d1)

# Fast version
d2 = np.sum(A * B.T, axis=1)
print(d2)

# Faster version
d3 = np.einsum("ij,ji->i", A, B)
print(d3)

[[0.05929652 0.18117115 0.02921185 0.99361793 0.04800246]
 [0.20349223 0.62080016 0.16316523 0.21271473 0.21406348]
 [0.94791932 0.15899386 0.83486011 0.26010131 0.91075891]
 [0.95473776 0.95924164 0.50892195 0.48454277 0.28881711]
 [0.64668084 0.0159172  0.15101882 0.96581615 0.39312768]]
[[0.11074691 0.14082841 0.4122541  0.59962314 0.03176925]
 [0.92172701 0.22491201 0.18325148 0.20600922 0.39658802]
 [0.78996281 0.90943581 0.83536614 0.09821266 0.99916101]
 [0.20947984 0.04417633 0.84052288 0.58636492 0.36485336]
 [0.11694256 0.65930162 0.24534224 0.76033858 0.90489405]]
[0.41038997 0.46720055 1.55940208 1.32379572 0.88586942]
[0.41038997 0.46720055 1.55940208 1.32379572 0.88586942]
[0.41038997 0.46720055 1.55940208 1.32379572 0.88586942]


In [23]:
# 21.交换一个矩阵的两行
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
